version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - challenge-meli-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - challenge-meli-network

  poi-service:
    image: poi-service:latest
    build:
      context: ./poi-service
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/portalInmobiliario
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    ports:
      - "8080:8080"
    networks:
      - challenge-meli-network

  pois-cliente:
    container_name: pois-cliente
    build:
      context: ./pois-cliente
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - challenge-meli-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - challenge-meli-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - challenge-meli-network

networks:
  challenge-meli-network:
    driver: bridge
