global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'poi-service'
    static_configs:
      - targets: ['poi-service:8080']

  - job_name: 'mongo'
    static_configs:
      - targets: ['mongo:27017']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
